name: APK Build

on:
  push:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@v10
        with:
          root-reserve-mb: 512
          swap-size-mb: 1024
          overprovision-lvm: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'
          remove-docker-images: 'true'

      - name: Checkout repository
        uses: actions/checkout@v4.2.0

      - name: Set Up JDK
        uses: actions/setup-java@v4.4.0
        with:
          distribution: 'oracle'
          java-version: '23'
          cache: 'gradle'

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Check free space
        run: |
          echo "Free space:"
          df -h

      # Run Build Project
      - name: Build gradle project
        run: ./gradlew build

      - name: Check free space
        run: |
          echo "Free space:"
          df -h

      # Create APK Release
      - name: Build apk
        run: ./gradlew assembleFullRelease

      - name: Check free space
        run: |
          echo "Free space:"
          df -h

      - name: Sign app APK
        uses: r0adkll/sign-android-release@v1
        id: sign_app
        with:
        releaseDirectory: /build/outputs/apk/release
        signingKeyBase64: ${{ secrets.SIGNING_KEY }}
        alias: ${{ secrets.ALIAS }}
        keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}

      # Upload Artifact Build
      - name: Upload APK Release
        uses: actions/upload-artifact@v4
        with:
          name: app-full-release
          path: ${{steps.sign_app.outputs.signedReleaseFile}}
